### PR TITLE
change image load from 3ch to 1ch

### PR DESCRIPTION
**Pull request by dhpollack**
This addresses issue #55.  One expects a 1 channel mask (resize based only on height and width) but you force this to become a 3 channel mask upon loading (mode="RGB").  Now we correctly get a 1 channel 8 bit mask.

### CODE REVIEW

**Comment by wesleyw72** [comment]
Good work but I think this is a duplicate of #33.

**Comment by dhpollack** [comment]
Kind of. But he assumes the image is a 32 bit encoding and I'm assuming it's 8 bit (which is more typical in ML).

**Comment by dhpollack** [comment]
[pillow mode docs](https://pillow.readthedocs.io/en/latest/handbook/concepts.html#modes)

**Comment by dhpollack** [comment]
gonna close, reopen if you want to add it.

**Pull request closed without merging**
